/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DB.CrudDB;
import control.Clients;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gotle
 */
public class PageClientsMenu extends javax.swing.JFrame {

    protected static DefaultTableModel model1;
    private CrudDB crudBD = new CrudDB();
    private ArrayList<Clients> clients = crudBD.getClients();

    /**
     * Creates new form PageClientsMenu
     */
    public PageClientsMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        model1 = (DefaultTableModel) tbl_clients.getModel();
        Iterator<Clients> iterator = clients.iterator();
        while (iterator.hasNext()) {
            Clients client = iterator.next();
            model1.addRow(new Object[]{
                client.getCompleteName(),
                client.getId(),
                client.getPhoneNumber(),
                client.getEmailAddress(),
                client.getAddress()});

        }
        tbl_clients.setModel(model1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_clients = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lbl_consultPeople = new javax.swing.JLabel();
        txt_consultPeople = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 600));
        setPreferredSize(new java.awt.Dimension(850, 600));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(840, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre / Razón Social", "ID / NIT", "Teléfono", "Email", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(tbl_clients);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, 800, 460));

        jPanel2.setBackground(new java.awt.Color(15, 120, 186));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(48, 153, 210));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Añadir Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 320, -1));

        lbl_consultPeople.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_consultPeople.setForeground(new java.awt.Color(255, 255, 255));
        lbl_consultPeople.setText("<html> <center>Buscar por <br> Nombre / Documento </html>");
        jPanel2.add(lbl_consultPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txt_consultPeople.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_consultPeopleKeyReleased(evt);
            }
        });
        jPanel2.add(txt_consultPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 190, -1));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new PageMenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new PageClients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_consultPeopleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_consultPeopleKeyReleased
        String input = txt_consultPeople.getText();
        if (input.isBlank()) {
            model1.setRowCount(0);
            model1 = (DefaultTableModel) tbl_clients.getModel();
            Iterator<Clients> iterator = clients.iterator();
            while (iterator.hasNext()) {
                Clients client = iterator.next();
                model1.addRow(new Object[]{
                    client.getName(),
                    client.getId(),
                    client.getPhoneNumber(),
                    client.getEmailAddress(),
                    client.getAddress()
                    });
            }
            tbl_clients.setModel(model1);
        } else {
            DefaultTableModel model = model1;
            model.setRowCount(0);
            // Filtra y muestra solo los datos que coincidan con la entrada del usuario
            for (Clients person : clients) {
                if (person.getId().toLowerCase().contains(input.toLowerCase()) || person.getName().toLowerCase().contains(input.toLowerCase())) {
                    model.addRow(new Object[]{person.getName(),
                    person.getId(),
                    person.getPhoneNumber(),
                    person.getEmailAddress(),
                    person.getAddress()});
                }
            }
            tbl_clients.setModel(model);
        }
    }//GEN-LAST:event_txt_consultPeopleKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageClientsMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageClientsMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageClientsMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageClientsMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageClientsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_consultPeople;
    private javax.swing.JTable tbl_clients;
    private javax.swing.JTextField txt_consultPeople;
    // End of variables declaration//GEN-END:variables
}
