/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DB.CrudBD;
import control.Clients;
import control.UseComponents;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Product;

/**
 *
 * @author gotle
 */
public class PageBillings extends javax.swing.JFrame {

    private DefaultTableModel model, model1;
    private CrudBD crudBD = new CrudBD();
    private ArrayList<Clients> clients = crudBD.getClients();

    /**
     * Creates new form PageBillings
     */
    public PageBillings() {
        initComponents();
        this.setLocationRelativeTo(null);
        model1 = (DefaultTableModel) tbl_consultPeople.getModel();
        Iterator<Clients> iterator = clients.iterator();

        while (iterator.hasNext()) {
            Clients client = iterator.next();
            model1.addRow(new Object[]{client.getId(),
                client.getName(),});

        }
        tbl_consultPeople.setModel(model1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbl_preview = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        txt_priceProducts = new javax.swing.JTextField();
        lbl_unitPrice = new javax.swing.JLabel();
        cbx_products = new javax.swing.JComboBox<>();
        lbl_products = new javax.swing.JLabel();
        cbx_typeProducts = new javax.swing.JComboBox<>();
        lbl_typeProducts = new javax.swing.JLabel();
        lbl_cantity = new javax.swing.JLabel();
        txt_totalPrice = new javax.swing.JTextField();
        lbl_totalPrice = new javax.swing.JLabel();
        btn_addBills = new javax.swing.JButton();
        lbl_infoBills = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_consultPeople = new javax.swing.JTable();
        lbl_consultPeople = new javax.swing.JLabel();
        txt_consultPeople = new javax.swing.JTextField();
        txt_cantity = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_previewBills = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_consultBills = new javax.swing.JTable();
        spn_billDate1 = new javax.swing.JSpinner();
        btn_filter = new javax.swing.JButton();
        lbl_intervalDates = new javax.swing.JLabel();
        lbl_billPersonType = new javax.swing.JLabel();
        cbx_billPersonType = new javax.swing.JComboBox<>();
        lbl_billDocument = new javax.swing.JLabel();
        txt_billDocument = new javax.swing.JTextField();
        spn_billDate2 = new javax.swing.JSpinner();
        btn_generatePdf = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(15, 120, 186));
        setPreferredSize(new java.awt.Dimension(882, 620));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(15, 120, 186));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(870, 620));

        jPanel2.setMinimumSize(new java.awt.Dimension(870, 620));
        jPanel2.setPreferredSize(new java.awt.Dimension(870, 620));

        lbl_preview.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_preview.setText("Previsualización");

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_priceProducts.setEditable(false);
        jPanel3.add(txt_priceProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, -1));

        lbl_unitPrice.setText("Precio / Unidad");
        jPanel3.add(lbl_unitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        cbx_products.setEnabled(false);
        cbx_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_productsActionPerformed(evt);
            }
        });
        jPanel3.add(cbx_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 340, -1));

        lbl_products.setText("Servicios / Productos");
        jPanel3.add(lbl_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cbx_typeProducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Consulta", "Imagenología", "Exámenes Clínicos", "Peluquería" }));
        cbx_typeProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_typeProductsActionPerformed(evt);
            }
        });
        jPanel3.add(cbx_typeProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, -1));

        lbl_typeProducts.setText("Tipo de Servicio");
        jPanel3.add(lbl_typeProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lbl_cantity.setText("Cantidad");
        jPanel3.add(lbl_cantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        txt_totalPrice.setEditable(false);
        jPanel3.add(txt_totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 340, -1));

        lbl_totalPrice.setText("Precio Total");
        jPanel3.add(lbl_totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        btn_addBills.setBackground(new java.awt.Color(48, 153, 210));
        btn_addBills.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_addBills.setForeground(new java.awt.Color(255, 255, 255));
        btn_addBills.setText("Añadir Factura");
        jPanel3.add(btn_addBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 260, 30));

        lbl_infoBills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_infoBills.setText("<html> <center>Ingrese Informacion del Producto <br> y Seleccione a una Persona </html>");
        jPanel3.add(lbl_infoBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tbl_consultPeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre"
            }
        ));
        tbl_consultPeople.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_consultPeopleMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_consultPeople);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 400, 310));

        lbl_consultPeople.setText("<html> <center>Buscar por <br> Nombre / Documento </html>");
        jPanel3.add(lbl_consultPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        txt_consultPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_consultPeopleActionPerformed(evt);
            }
        });
        txt_consultPeople.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_consultPeopleKeyTyped(evt);
            }
        });
        jPanel3.add(txt_consultPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 190, -1));

        txt_cantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        txt_cantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txt_cantityStateChanged(evt);
            }
        });
        jPanel3.add(txt_cantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 190, -1));

        tbl_previewBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Cantidad", "Precio Total"
            }
        ));
        jScrollPane2.setViewportView(tbl_previewBills);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(lbl_preview))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_preview)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Registrar Facturas", jPanel2);

        jPanel1.setMinimumSize(new java.awt.Dimension(870, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 620));

        tbl_consultBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_consultBills);

        spn_billDate1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1672613340000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        btn_filter.setBackground(new java.awt.Color(48, 153, 210));
        btn_filter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_filter.setForeground(new java.awt.Color(255, 255, 255));
        btn_filter.setText("Filtrar");

        lbl_intervalDates.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_intervalDates.setText("Ingresar Intervalo de Fechas");

        lbl_billPersonType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_billPersonType.setText("Tipo de Persona");

        cbx_billPersonType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Persona Natural", "Persona Juridica" }));

        lbl_billDocument.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_billDocument.setText("Ingresar Documento");

        spn_billDate2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1672613460000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        btn_generatePdf.setBackground(new java.awt.Color(255, 255, 204));
        btn_generatePdf.setText("Generar PDF");

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_generatePdf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_billPersonType)
                            .addComponent(cbx_billPersonType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_billDocument)
                            .addComponent(txt_billDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lbl_intervalDates))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spn_billDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(spn_billDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generatePdf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_billPersonType)
                        .addGap(4, 4, 4)
                        .addComponent(cbx_billPersonType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_billDocument)
                        .addGap(4, 4, 4)
                        .addComponent(txt_billDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_intervalDates)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spn_billDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spn_billDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Consultar Facturas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new PageMenu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new PageMenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbx_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_productsActionPerformed
        txt_cantity.setValue(1);
        ArrayList<Product> productsByType = crudBD.getProducts(String.valueOf(cbx_typeProducts.getSelectedItem()));
        for (Product elemento : productsByType) {
            if (elemento.getName().equals(cbx_products.getSelectedItem())) {
                txt_priceProducts.setText(String.valueOf(elemento.getPrice()));
                txt_totalPrice.setText(String.valueOf(elemento.getPrice()));
            }
        }
    }//GEN-LAST:event_cbx_productsActionPerformed

    private void cbx_typeProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_typeProductsActionPerformed
        txt_priceProducts.setText("");
        txt_totalPrice.setText("");
        txt_cantity.setValue(1);
        cbx_products.removeAllItems();
        if (cbx_typeProducts.getSelectedIndex() == 0) {
            cbx_products.setEnabled(false);
        } else {
            cbx_products.setEnabled(true);
            for (Product elemento : crudBD.getProducts(String.valueOf(cbx_typeProducts.getSelectedItem()))) {
                cbx_products.addItem(elemento.getName());
            }
        }
    }//GEN-LAST:event_cbx_typeProductsActionPerformed

    private void txt_cantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txt_cantityStateChanged
        txt_totalPrice.setText(UseComponents.totalPrice(txt_cantity, txt_priceProducts));
    }//GEN-LAST:event_txt_cantityStateChanged

    private void tbl_consultPeopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_consultPeopleMouseClicked
        int seleccionFila = tbl_consultPeople.rowAtPoint(evt.getPoint());
        String selectedId = String.valueOf(tbl_consultPeople.getValueAt(seleccionFila, 0));
        JOptionPane.showMessageDialog(null, selectedId);

    }//GEN-LAST:event_tbl_consultPeopleMouseClicked

    private void txt_consultPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_consultPeopleActionPerformed


    }//GEN-LAST:event_txt_consultPeopleActionPerformed

    private void txt_consultPeopleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_consultPeopleKeyTyped
        String input = txt_consultPeople.getText();
        DefaultTableModel model = new DefaultTableModel();

        if (input.isEmpty()) {
            // Si el campo de texto está vacío, muestra todos los datos originales
            tbl_consultPeople.setModel(model1);
        } else {
            // Filtra y muestra solo los datos que coincidan con la entrada del usuario
            for (Clients person : clients) {
                if (person.getId().contains(input) || person.getName().contains(input)) {
                    model.addRow(new Object[]{person.getId(), person.getName()});
                }
            }
           tbl_consultPeople.setModel(model);
        }  
    }//GEN-LAST:event_txt_consultPeopleKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageBillings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageBillings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageBillings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageBillings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageBillings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addBills;
    private javax.swing.JButton btn_filter;
    private javax.swing.JButton btn_generatePdf;
    private javax.swing.JComboBox<String> cbx_billPersonType;
    private javax.swing.JComboBox<String> cbx_products;
    private javax.swing.JComboBox<String> cbx_typeProducts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_billDocument;
    private javax.swing.JLabel lbl_billPersonType;
    private javax.swing.JLabel lbl_cantity;
    private javax.swing.JLabel lbl_consultPeople;
    private javax.swing.JLabel lbl_infoBills;
    private javax.swing.JLabel lbl_intervalDates;
    private javax.swing.JLabel lbl_preview;
    private javax.swing.JLabel lbl_products;
    private javax.swing.JLabel lbl_totalPrice;
    private javax.swing.JLabel lbl_typeProducts;
    private javax.swing.JLabel lbl_unitPrice;
    private javax.swing.JSpinner spn_billDate1;
    private javax.swing.JSpinner spn_billDate2;
    private javax.swing.JTable tbl_consultBills;
    private javax.swing.JTable tbl_consultPeople;
    private javax.swing.JTable tbl_previewBills;
    private javax.swing.JTextField txt_billDocument;
    private javax.swing.JSpinner txt_cantity;
    private javax.swing.JTextField txt_consultPeople;
    private javax.swing.JTextField txt_priceProducts;
    private javax.swing.JTextField txt_totalPrice;
    // End of variables declaration//GEN-END:variables
}
